version: '2.1'

services:
  zoo1:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zoo1
    container_name: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka1:
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    depends_on:
      - zoo1

  zoo2:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zoo2
    container_name: zoo2
    ports:
      - "2182:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka2:
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafka2
    container_name: kafka2
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zoo2:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    depends_on:
      - zoo2

  mirrormaker2:
    image: confluentinc/cp-kafka:7.3.2
    hostname: mirrormaker2
    container_name: mirrormaker2
    volumes:
      - ./docker-kafka-config/log4j.properties:/etc/kafka/connect-log4j.properties
      - ./docker-kafka-config/mirrormaker2.properties:/etc/kafka/mirrormaker2.properties
    depends_on:
      - kafka1
      - kafka2
    command: >
      bash -c "
        echo 'Waiting for Kafka brokers to be available...' &&
        sleep 10 &&
        echo 'Starting MirrorMaker 2...' &&
        /usr/bin/connect-mirror-maker /etc/kafka/mirrormaker2.properties"
    environment:
      KAFKA_LOG4J_OPTS: "-Dlog4j.configuration=file:/etc/kafka/connect-log4j.properties"
      
    # volumes:
    #   - ./docker-kafka-config/log4j.properties:/etc/kafka/connect-log4j.properties
    # depends_on:
    #   - kafka1
    #   - kafka2
    # command: bash -c "sleep infinity"
    # command: >
    #   bash -c "echo 'clusters = kafka1, kafka2
    #   kafka1.bootstrap.servers = kafka1:9092
    #   kafka2.bootstrap.servers = kafka2:9092
    #   kafka1->kafka2.enabled = true
    #   kafka1->kafka2.topics = .*
    #   kafka1->kafka2.groups = .*' > /tmp/mirrormaker2.properties && 
    #   connect-mirror-maker /tmp/mirrormaker2.properties"
